### ISSUE TITLE
Add RFI related endpoints.

### ISSUE THREAD

**Issue by andrerenard** [chime-experiment/coco#169]
In the next release the kotekan GPU config will include the following new (or updated) endpoints:

```
updatable_config:
  bad_inputs:
    kotekan_update_endpoint: "json"
    # These inputs are assumed to be in cylinder order
    bad_inputs: []
  rfi_zeroing_toggle:
    kotekan_update_endpoint: "json"
    rfi_zeroing: False
  rfi_sk_record:
    kotekan_update_endpoint: "json"
    write_to: /mnt/gong/RFI/test_sk/
    write_to_disk: false
  rfi_var_record:
    kotekan_update_endpoint: "json"
    write_to: /mnt/gong/RFI/test_var/
    write_to_disk: false
  rfi_var_element_index:
    kotekan_update_endpoint: "json"
    # This element should be given in cylinder input order,
    # not correlator/FPGA input order.
    element_index: 840
```

We need to include these in `coco`'s config.
