### ISSUE TITLE
request data gets lost between multiple coco-forwards

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#171]
using the following endoint configs,

update-bad-inputs:
```
type: POST
values:
  tag: str
  start_time: float
  bad_inputs: list
call:
  coco:
    - update-bad-inputs-cluster
    - update-bad-inputs-receiver
  forward: null
```

and
update-bad-inputs-receiver:
```
type: POST
group: receiver_nodes
values:
  tag: str
  start_time: float
  bad_inputs: list
call:
  forward: updatable_config/flagging
save_state: receiver/updatable_config/flagging
```

we get the warning:
```
[WARNING] [coco.endpoint.update-bad-inputs-receiver] update-bad-inputs-receiver requires value 'tag'.
```
