### ISSUE TITLE
client: use a more verbose report type by default

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#190]
```


[cahofer@cndhn ~]$ coco start

start-cluster:

  gps-time:

    get-frame0-time: {'200': 1}

    success: true

  start: {'0': 144, '402': 96}

  success: true

start-receiver:

  start: {'402': 1}

  success: true

status-cluster:

  failed_checks:

    status-cluster:

      reply:

        missing: {'[running]': 1}

  status: {'0': 144, '200': 96}

  success: false

success: false

version-cluster:

  failed_checks:

    version-cluster:

      reply:

        not_identical: {'[all]': 1}

  success: false

  version: {'0': 11, '200': 229}


```
