### ISSUE TITLE
save_reply_to_state overwrites path instead of inserting

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#199]
The line `save_reply_to_state: cluster` in
```
description: "Get dynamic frequency map from fpga_master and insert into cluster config."
group: fpga_master
enforce_group: True
call:
  forward:
    - name: get-frequency-map
      # kill cluster if fpga_master relies with {}
      reply:
        type:
          fmap: dict
      on_failure:
        call: stop-cluster
      save_reply_to_state: cluster
callable: False
call_on_start: True
# The F-Engine needs 5min to restart and the frame0-time is checked every 5min to detect restarts.
# The frequency map should never change without a restart / the frame0-time changing as well.
# We therefor only check once per hour just to make sure nothing is going seriously wrong.
schedule:
  period: 61m
```

Overwrites the whole section `cluster`, instead of inserting the one key into it.
