### ISSUE TITLE
Add option to act on forward-call failure

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#75]
For scheduling a coco endpoint that calls status (#44 ) and restarts every node that doesn't respond with `running: True`, config options to define that behaviour is needed and the functionality needs to be added to `Endpoint.call()`. The config in the endpoint config could look like:
```
call:
  forward:
    - <endpoint name (e.g. status)>:
      on_failure:
        call: restart
      reply:
        running:
          value: True
```
This will call restart for every node that failed for the conditions specified with `reply: running: value: True`.
Needs functionality to pass single host to endpoint call: 
Needs functionality to test the values in a reply:
