### ISSUE TITLE
Add option to check the value of a forward-call reply

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#77]
When doing a forward-call (to an external endpoint on a configured group of hosts), we need to add the option to check the values of the reply. Needed by #75

e.g.:
```
call:
  forward:
    - get-frame0-time:
      # make sure GPS server didn't reply with {} (happens if it just started)
      reply:
        frame0_time:
          type: list
        frame0_nano:
          value: 0
```
