### ISSUE TITLE
Add option to act on forward-call failure: call another coco endpoint

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#78]
Just like #75 but not pass a host to the endpoint call, so that a failure in any forward-reply results in calling another coco endpoint that would forward to whatever group it has configured.
e.g.:
```
call:
  forward:
    <endpoint name (e.g. status)>:
      on_failure:
        call: restart
      reply:
        running:
          value: True
```
