### ISSUE TITLE
Refactor all checks on calls into a class

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#87]
Checks at the moment are read from config:
```
call:
  forward:
    reply:
      type:
        <name>: <type>
      value:
        <name>: <value>
```
(also checks for missing fields in the reply)
and
```
before:
  identical:
    - <name>
    ...
after:
  ...
```

`Endpoint` keeps this configuration in dictionaries and goes through the options when it actually does the checks. Move this into a `Check` class and possibly sub classes for the different checks. A class like `Action` could implement  the `on_failure` part. Then the part that saves the reply of the forward call needs to find a new place.
